version: '3'

services:
  # MySQL service
  mysql:
    image: mysql:8.0.30-debian
    container_name: mysql-container
    environment:
       - MYSQL_DATABASE=ems1
       - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"  
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
      # Map container port 3306 to host port 3308
    
  # Tomcat service with Spring Boot JSF application
#  tomcat:
#    image: tomcat:9.0.84-jdk17-temurin
#    container_name: tomcat-container
#    restart: alwayssa
#    depends_on:
#      - mysql
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./target/EmployeManagementSystem-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/app.war

  # Spring Boot JSF application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-jsf-container
    restart: always
    depends_on:
      - mysql
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/jfs
    ports:
      - "8080:8080"
